name: jappeos_installer
description: "Installer app for JappeOS."
publish_to: 'none'

version: 0.0.9

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shadcn_flutter:
    git:
      url: https://github.com/JappeOS/shadcn_flutter.git
      ref: master

  jappeos_services:
    git:
      url: https://github.com/JappeOS/jappeos_services.git
      ref: dev

  provider: ^6.0.3
  widget_and_text_animator: ^1.1.5
  package_info_plus: ^9.0.0
  crypt: ^4.3.1
  flutter_map: ^8.3.0
  jovial_svg: ^1.1.29
  latlong2: ^0.9.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/maps/world.svg
    - assets/timezones/combined_simplified.json
